### ISSUE TITLE
Figure out how to put Hatch hook on robot

### ISSUE THREAD

**Issue by stgraham11** [5530-Lawnmowers/2019-Season#17]
# Context
Design was decided upon, now just need to figure out how to attach it to the robot

# Notes
Need a way to extend the hook and latch for durable resistance against collision. 

# Design
Hook Design prototyped
Mount needs to be low enough to collect hatch from station.

**Comment by BigMrHall** [comment]
We need to be able to extend the hook and insure it locks.  Plan is to use servo to move and latch into position
